### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by frownbreaker** [borpin/node-red-contrib-octopus#9]
Hi there

Thanks for developing this node-red code - I understand it's under development. I think I need to use npm install <git repo url><git remote url> that resolves to a folder containing a program described by a package.json file. Not sure what that would look like for your software?

I normally install node-red contributions via the pallet tool and saw that I have to install this via github. 
I don't know how to do this and saw this command in the previous issue

`root@orangepione:~# **npm install github.com:borpin/node-red-contrib-octopus.git**`

When I run that (after updating my Armbian) install running on an Orange Pi 

This is the error I get.
```
npm ERR! Linux 3.4.113-sun8i
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "github.com:borpin/node-red-contrib-octopus.git"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10

npm ERR! Unsupported URL Type: github.com:borpin/node-red-contrib-octopus.git
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

```
This is the contents of   **/root/npm-debug.log**

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'github.com:borpin/node-red-contrib-octopus.git' ]
2 info using npm@3.10.10
3 info using node@v6.17.1
4 verbose config Skipping project config: /root/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData github.com:borpin/node-red-contrib-octopus.git
9 silly fetchPackageMetaData Error: Unsupported URL Type: github.com:borpin/node-red-contrib-octopus.                                                                                                                                        git
9 silly fetchPackageMetaData     at parseUrl (/usr/lib/node_modules/npm/node_modules/npm-package-arg/                                                                                                                                        npa.js:186:13)
9 silly fetchPackageMetaData     at npa (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.j                                                                                                                                        s:79:12)
9 silly fetchPackageMetaData     at module.exports (/usr/lib/node_modules/npm/node_modules/realize-pa                                                                                                                                        ckage-specifier/index.js:12:15)
9 silly fetchPackageMetaData     at fetchPackageMetadata (/usr/lib/node_modules/npm/lib/fetch-package                                                                                                                                        -metadata.js:54:12)
9 silly fetchPackageMetaData     at fetchMetadataWithVersion (/usr/lib/node_modules/npm/lib/install/d                                                                                                                                        eps.js:228:14)
9 silly fetchPackageMetaData     at /usr/lib/node_modules/npm/lib/install/deps.js:241:16
9 silly fetchPackageMetaData     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:                                                                                                                                        35
9 silly fetchPackageMetaData     at Array.forEach (native)
9 silly fetchPackageMetaData     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:                                                                                                                                        11
9 silly fetchPackageMetaData     at Array.forEach (native)
9 silly fetchPackageMetaData  error for github.com:borpin/node-red-contrib-octopus.git Error: Unsuppo                                                                                                                                        rted URL Type: github.com:borpin/node-red-contrib-octopus.git
9 silly fetchPackageMetaData     at parseUrl (/usr/lib/node_modules/npm/node_modules/npm-package-arg/                                                                                                                                        npa.js:186:13)
9 silly fetchPackageMetaData     at npa (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.j                                                                                                                                        s:79:12)
9 silly fetchPackageMetaData     at module.exports (/usr/lib/node_modules/npm/node_modules/realize-pa                                                                                                                                        ckage-specifier/index.js:12:15)
9 silly fetchPackageMetaData     at fetchPackageMetadata (/usr/lib/node_modules/npm/lib/fetch-package                                                                                                                                        -metadata.js:54:12)
9 silly fetchPackageMetaData     at fetchMetadataWithVersion (/usr/lib/node_modules/npm/lib/install/d                                                                                                                                        eps.js:228:14)
9 silly fetchPackageMetaData     at /usr/lib/node_modules/npm/lib/install/deps.js:241:16
9 silly fetchPackageMetaData     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:                                                                                                                                        35
9 silly fetchPackageMetaData     at Array.forEach (native)
9 silly fetchPackageMetaData     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:                                                                                                                                        11
9 silly fetchPackageMetaData     at Array.forEach (native)
10 silly rollbackFailedOptional Starting
11 silly rollbackFailedOptional Finishing
12 silly runTopLevelLifecycles Finishing
13 silly install printInstalled
14 verbose stack Error: Unsupported URL Type: github.com:borpin/node-red-contrib-octopus.git
14 verbose stack     at parseUrl (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:186:1                                                                                                                                        3)
14 verbose stack     at npa (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:79:12)
14 verbose stack     at module.exports (/usr/lib/node_modules/npm/node_modules/realize-package-specif                                                                                                                                        ier/index.js:12:15)
14 verbose stack     at fetchPackageMetadata (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js                                                                                                                                        :54:12)
14 verbose stack     at fetchMetadataWithVersion (/usr/lib/node_modules/npm/lib/install/deps.js:228:1                                                                                                                                        4)
14 verbose stack     at /usr/lib/node_modules/npm/lib/install/deps.js:241:16
14 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
14 verbose stack     at Array.forEach (native)
14 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
14 verbose stack     at Array.forEach (native)
15 verbose cwd /root
16 error Linux 3.4.113-sun8i
17 error argv "/usr/bin/node" "/usr/bin/npm" "install" "github.com:borpin/node-red-contrib-octopus.git"
18 error node v6.17.1
19 error npm  v3.10.10
20 error Unsupported URL Type: github.com:borpin/node-red-contrib-octopus.git
21 error If you need help, you may report this error at:
21 error     <https://github.com/npm/npm/issues>
22 verbose exit [ 1, true ]

**Comment by borpin** [comment]
> `root@orangepione:~# **npm install github.com:borpin/node-red-contrib-octopus.git**`

Did you run it with the `**`?

It should work according to the docs.

https://docs.npmjs.com/cli/install
